### ISSUE TITLE
Question about the training datasets and test datasets

### ISSUE THREAD

**Issue by Wilboludriver** [wjn1996/InstructGraph#11]
Dear Author,

Thank you for your great work on this filed! I found the benchmark datasets in your repo are stored as `data/other_benchmarks/MMLU/mmlu_dataset.json`. And I'm wondering whether the datasets are directly downloaded from Huggingface or they need some extra processing?

Thanks very much for reading!

Best,
Wilb

**Comment by wjn1996** [comment]
Thank you for your attention. The data processing script is shown in the path: data/other_benchmarks/MMLU/Merge_MMLU.ipynb

**Comment by Wilboludriver** [comment]
Thank you very much!
