### ISSUE TITLE
Question about the full InstructGraph Dataset

### ISSUE THREAD

**Issue by RManLuo** [wjn1996/InstructGraph#12]
Hello, thank you for sharing this inspiring work. I noticed that there are only 2000 and 3920 samples for instruction training and testing provided in the data/instruction_dataset/released directory. In your paper, you mentioned constructing a dataset with approximately 1.6 million samples. Would it be possible for you to share the complete InstructGraph dataset? Thank you once again for your efforts!

**Comment by wjn1996** [comment]
We will release the whole corpus and the corresponding model on hf after the notification of the conference (about in May).
If you want to construct the corpus by yourself, you can follow the jupyter notebook in 'https://github.com/wjn1996/InstructGraph/tree/main/data'.

 Thank you for your positive attention.

**Comment by RManLuo** [comment]
Thank you for your response! I am currently working on constructing the corpus myself. I noticed that you utilized a pre-processed Freebase. Could you please provide a link to the Freebase so that I can create the GrailQA and WebQSP datasets?

**Comment by wjn1996** [comment]
Hello, we release the sft data and you can get it from https://huggingface.co/datasets/wjn1996/InstructGraph. Enjoy!

**Comment by RManLuo** [comment]
> Hello, we release the sft data and you can get it from https://huggingface.co/datasets/wjn1996/InstructGraph. Enjoy!

Thanks for your hard work!
