### ISSUE TITLE
有在中文的数据集上做过实验么？

### ISSUE THREAD

**Issue by noobexplore** [wjn1996/InstructGraph#15]

**Comment by wjn1996** [comment]
Sorry, all the tasks were finished in English. We didn't try on the Chinese dataset, but we think it could adapt to this scenario if choose Chinese LLM.

**Comment by noobexplore** [comment]
谢谢回复，确实我感觉你们的思路就是让LLM去适应这样的一种代码风格去表征图数据，所以可以利用中文LLM微调你们的数据也能适配中文还是说可能得自己构造中文的数据集。

**Comment by wjn1996** [comment]
我们的数据都是英文，所以即便是中文模型也不一定可以很好地适配中文。不过你们可以按照code format模式构造中文图指令数据并自行微调。数据处理和代码都在Jupyter中；中文模型可自行选择chatglm，baichuan等。
