### ISSUE TITLE
您好，请问code-format数据微调后，通用知识的回答能力如何，是否可以结合一些通用的问答数据避免通用知识的灾难性遗忘，如果混合一部分通用的数据，会对DPO训练带来影响吗

### ISSUE THREAD

**Issue by jacks-tang** [wjn1996/InstructGraph#17]
您好，请问code-format数据微调后，通用知识的回答能力如何，是否可以结合一些通用的问答数据避免通用知识的灾难性遗忘，如果混合一部分通用的数据，会对DPO训练带来影响吗

**Comment by wjn1996** [comment]
您好，我们在训练的时候只针对Graph的指令数据进行训练，但是针对通用的QA能力依然也有，但是效果会下降。当然在训练时加入其他通用的QA数据也可以避免这个问题。
在DPO中如果混合一些其他的偏好数据应该可以缓解模型对于通用偏好能力的灾难遗忘问题，不过对Graph的性能影响没有单独测试过。

**Comment by jacks-tang** [comment]
Thanks
